/**
 * Default arity (argument count) for every primitive procedure.
 *
 * The Logo parser needs to know how many arguments each procedure consumes so
 * it can parse a call correctly. User-defined procedures register their arity
 * when their `TO ... END` block is parsed; primitives use this table.
 *
 * For variable-arity primitives (usable as `(SUM 1 2 3)`), the value here is
 * the default arity used without parentheses; the parser reads all arguments
 * up to `)` when parentheses are present.
 */

export const PRIMITIVE_ARITY: Record<string, number> = {
  // --- Turtle graphics ---
  FORWARD: 1, FD: 1, BACK: 1, BK: 1, LEFT: 1, LT: 1, RIGHT: 1, RT: 1,
  SETXY: 2, SETPOS: 1, SETX: 1, SETY: 1, SETHEADING: 1, SETH: 1, HOME: 0,
  PENUP: 0, PU: 0, PENDOWN: 0, PD: 0, SETPENCOLOR: 1, SETPC: 1,
  SETBACKGROUND: 1, SETBG: 1, CLEARSCREEN: 0, CS: 0, CLEAN: 0,
  HIDETURTLE: 0, HT: 0, SHOWTURTLE: 0, ST: 0, ARC: 2, LABEL: 1,
  GETXY: 0, XCOR: 0, YCOR: 0, HEADING: 0, PENCOLOR: 0, PC: 0,
  BACKGROUND: 0, BG: 0, PENSIZE: 0, PENMODE: 0, WINDOW: 0, WRAP: 0,
  FENCE: 0, SETPEN: 1, SETPENSIZE: 1, SETPALETTE: 2, PALETTE: 1,
  SETSCRUNCH: 1, SCRUNCH: 0, SHOWNP: 0, TURTLEP: 0, PENDOWNP: 0,
  FILL: 0, SETLABELHEIGHT: 1, LABELSIZE: 0, SETPENPATTERN: 1,
  PENPATTERN: 0, TEXTSCREEN: 0, SPLITSCREEN: 0, FULLSCREENS: 0,
  DRAW: 0, SAVEPICT: 1, LOADPICT: 1,

  // --- Control ---
  IF: 2, IFELSE: 3, TEST: 1, IFTRUE: 1, IFT: 1, IFFALSE: 1, IFF: 1, REPEAT: 2,
  WHILE: 2, UNTIL: 2, 'DO.WHILE': 2, 'DO.UNTIL': 2, FOR: 2, DOTIMES: 2,
  FOREVER: 1, CATCH: 2, THROW: 1, STOP: 0, OUTPUT: 1, OP: 1, RUN: 1,
  REPCOUNT: 0, CASE: 2, GO: 1, RETURN: 1, BREAK: 0, CONTINUE: 0, TOPLEVEL: 0,

  // --- Arithmetic ---
  SUM: 2, DIFFERENCE: 2, PRODUCT: 2, QUOTIENT: 2, REMAINDER: 2,
  MODULO: 2, POWER: 2, SQRT: 1, SIN: 1, COS: 1, ARCTAN: 1, RADSIN: 1,
  RADCOS: 1, RADARCTAN: 1, INT: 1, ROUND: 1, ABS: 1, MINUS: 1, EXP: 1,
  LN: 1, LOG10: 1, RANDOM: 1, RRANDOM: 1, SEEDRANDOM: 1, LESSP: 2,
  GREATERP: 2, LESSEQUALP: 2, GREATEREQUALP: 2, EQUALP: 2, NOTEQUALP: 2,
  AND: 2, OR: 2, NOT: 1, BITAND: 2, BITOR: 2, BITXOR: 2, BITNOT: 1,
  ASHIFT: 2, LSHIFT: 2, RSHIFT: 2,

  // --- Lists ---
  FIRST: 1, LAST: 1, BUTFIRST: 1, BF: 1, BUTLAST: 1, BL: 1, ITEM: 2,
  FPUT: 2, LPUT: 2, SENTENCE: 2, SE: 2, LIST: 2, REVERSE: 1, COUNT: 1,
  MEMBERP: 2, MEMBER: 2, REMDUP: 1, PICK: 1, EMPTYP: 1, LISTP: 1,
  COMBINE: 2, FIRSTS: 1, BUTFIRSTS: 1, BUTLASTS: 1,

  // --- Words ---
  WORD: 2, CHAR: 1, ASCII: 1, LOWERCASE: 1, UPPERCASE: 1, FORM: 2,
  PARSE: 1, UNPARSE: 1, BACKSLASHEDP: 1, SUBSTRING: 2, SUBSTRINGP: 2,
  BEFOREP: 2, WORDP: 1, NUMBERP: 1,

  // --- I/O ---
  PRINT: 1, SHOW: 1, TYPE: 1, READLIST: 0, READWORD: 0, READCHAR: 0,
  OPENREAD: 1, OPENWRITE: 1, OPENAPPEND: 1, CLOSE: 1, ALLOPEN: 0,
  CLOSEALL: 0, SAVE: 1, LOAD: 1, ERASE: 1, SETREAD: 1, SETWRITE: 1,
  EOFP: 0, SETPREFIX: 1, PREFIX: 0, READPOS: 0, SETREADPOS: 1,
  SETWRITEPOS: 1, WRITEPOS: 0,

  // --- Higher-order ---
  MAP: 2, MAPSE: 2, FILTER: 2, FIND: 2, REDUCE: 2, APPLY: 2, INVOKE: 2,
  CASCADE: 3, CASCADE2: 4, FOREACH: 2, CROSSMAP: 2, TRANSFER: 2, TEXT: 1,
  DEFINE: 2, DEF: 2, COPYDEF: 2, MACROEXPAND: 1, MACROP: 1, DEFINEDP: 1,

  // --- Workspace ---
  MAKE: 2, NAME: 2, THING: 1, BURY: 1, BURIED: 1, BURIEDP: 1, BURYALL: 0,
  BURYNAME: 1, UNBURY: 1, UNBURYALL: 0, CONTENTS: 0, PROCEDUREP: 1,
  PRIMITIVEP: 1, PO: 1, POPS: 1, POT: 1, POTS: 0, PLIST: 1, ALLOWGETSET: 0,

  // --- Arrays ---
  ARRAY: 1, ARRAYTOLIST: 1, LISTTOARRAY: 1, SETITEM: 3, ARRAYDIMS: 1,
  ARRAYP: 1,

  // --- Properties ---
  GPROP: 2, PPROP: 3, REMPROP: 2, PLISTS: 0, PROPS: 1,

  // --- Misc ---
  TIME: 0, TIMEFORMAT: 1, SETTIMEFORMAT: 1, HELP: 1,

  // --- Terrapin / Apple Logo compatibility ---
  PR: 1, CT: 0, CLEARTEXT: 0, TT: 1, TURTLETEXT: 1, SETFONT: 3, SETTEXTSIZE: 1, ALERT: 1, SAY: 1,
  READ: 0, RC: 0, RL: 0, 'KEY?': 0, KEYP: 0, 'MOUSEDOWN?': 0, 'BUTTON?': 0, BUTTONP: 0, MOUSE: 0, MOUSEPOS: 0,
  FS: 0, FULLSCREEN: 0, SS: 0, TS: 0,
  SETW: 1, SETWIDTH: 1, SETPENWIDTH: 1, SETPW: 1, WIDTH: 0, PENWIDTH: 0, PW: 0,
  PX: 0, PENREVERSE: 0, PE: 0, PENERASE: 0, PPT: 0, PENPAINT: 0, PENNORMAL: 0,
  DOT: 0, STAMPOVAL: 2, STAMPRECT: 2, STAMP: 0, 'DOT?': 0, DOTP: 0, COLORUNDER: 0, COLORS: 0, PALETTECOLORS: 0,
  SETBGCOLOR: 1, POS: 0, TOWARDS: 1, DISTANCE: 1,
  TELL: 1, TELLALL: 2, '.WHO': 0, ALLTURTLES: 0, SETT: 1, BOUNDS: 0, ARCR: 2, ARCL: 2, SETBGPATTERN: 1, SETSPEED: 1, SETBOUNDS: 1,
  '.LT': 2, '.GT': 2, '.LE': 2, '.GE': 2, '.EQ': 2, '.NE': 2, WHO: 0, TURTLES: 0, SETTURTLES: 1, ASK: 2, EACH: 1, DECLARE: 2, 'DECLARED?': 1,
  SETSHAPE: 1, LOADSHAPE: 1, SHAPE: 0, LOCKSHAPE: 0, UNLOCKSHAPE: 0, SNAP: 2, LOADSNAP: 1, SAVESNAP: 1,
  SETTS: 1, SETTURTLESIZE: 1, TURTLESIZE: 0, SETVELOCITY: 1, VELOCITY: 0, SETXVEL: 1, SETYVEL: 1,
  SETROTATION: 1, SETSPIN: 1, BOUNCE: 0, FREEZE: 0, UNFREEZE: 0,
  WHEN: 2, LAUNCH: 1, HALT: 0, HALTALL: 0, WAIT: 1, PAUSE: 0, PLAY: 1, TONE: 2, BEEP: 0,
  SETTIMER: 1, CLEARTIMER: 0, MILLISECONDS: 0, TIMEMILLI: 0, TIMER: 0, DATE: 0,
  LOCAL: 1, LMAKE: 2, LOCALMAKE: 2, GLOBAL: 1, PPROPS: 2, ALIAS: 2, IGNORE: 1, QUOTE: 1, ERROR: 0,
  'EMPTY?': 1, 'EQUAL?': 2, 'LIST?': 1, 'WORD?': 1, 'NUMBER?': 1, 'MEMBER?': 2, 'ARRAY?': 1, 'BEFORE?': 2,
  'PENDOWN?': 0, 'SHOWN?': 0, 'NOTEQUAL?': 2, 'LESS?': 2, 'GREATER?': 2, 'SUBSTRING?': 2, 'DEFINED?': 1,
  'PROCEDURE?': 1, 'PRIMITIVE?': 1, 'EOF?': 0, 'NAME?': 1, 'THING?': 1, NAMEP: 1,
  BUTMEMBER: 2, REMOVE: 2, PI: 0, 'SETPC.NAME': 1, RANDOM0: 1, AGET: 2, APUT: 3, PEN: 0, COLORINDEX: 1,
  LBAPPEND: 1, LBREMOVE: 1, LBINSERT: 1, SETTEXT: 1, SETVALUE: 1, SETSIZE: 1, SETPOSITION: 1, SETTOOLTIP: 1,
  SETCHECKED: 1, SETMIN: 1, SETMAX: 1, SETSTEP: 1, SETCAPTION: 1, LBCLEAR: 0, FOCUS: 0, ENABLE: 0, DISABLE: 0,
  'SHOW.OBJECT': 0, 'HIDE.OBJECT': 0, LBCOUNT: 0, LBSELECTION: 0, LBITEM: 1, VALUE: 0, 'CHECKED?': 0,
  SIZE: 0, POSITION: 0, 'TEXT.OF': 0, 'LABEL.TEXT': 1, 'SETXY.IMPL': 2,
}

/** Variable-arity primitives that accept 2+ args when parenthesized. */
export const VARIABLE_ARITY: Record<string, true> = {
  SUM: true, DIFFERENCE: true, PRODUCT: true, QUOTIENT: true,
  SENTENCE: true, SE: true, LIST: true, WORD: true, FPUT: true, LPUT: true,
  AND: true, OR: true, PR: true, LOCAL: true, GLOBAL: true, RANDOM: true, PRINT: true, SHOW: true, TYPE: true,
  STAMPOVAL: true, STAMPRECT: true, DOT: true, TOWARDS: true, DISTANCE: true, SETFONT: true, SNAP: true, TELLALL: true, SETXY: true,
}
